/**
 * @file diseaseDatabase.js
 * @description Comprehensive Ethiopian Livestock Disease Reference Database.
 * Covers major endemic, epidemic, and zoonotic diseases affecting cattle, sheep,
 * goats, poultry, camels, and equines across Ethiopian agro-ecological zones.
 */

const LIVESTOCK_DISEASES = [
  {
    id: 'FMD',
    nameEn: 'Foot-and-Mouth Disease (FMD)',
    nameAm: 'የእግርና የአፍ በሽታ',
    nameOm: 'Dhukkuba Miillaa fi Afaanii',
    animalTypes: ['CATTLE', 'SHEEP', 'GOAT', 'PIG'],
    category: 'VIRAL',
    isZoonotic: false,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'HIGH',
    transmissionMode: 'Direct contact, aerosol, contaminated feed/water',
    incubationDays: { min: 2, max: 14 },
    symptomsEn: 'High fever (40-41°C), vesicles/blisters on tongue, lips, gums, feet, and teats. Excessive drooling, lameness, reluctance to eat, sudden drop in milk production.',
    symptomsAm: 'ከፍተኛ ትኩሳት፣ በምላስ፣ በከንፈር፣ በጥፍር መካከል ዕባጭ/ብጉር መፈጠር። ምራቅ ማበዝ፣ መላንጠጥ፣ የወተት ምርት ማሽቆልቆል።',
    treatmentEn: 'No specific antiviral treatment. Supportive care: wound cleaning with mild antiseptic (Potassium Permanganate 1:1000), anti-inflammatory drugs, soft feed, isolation. Report immediately to Woreda Veterinary Office.',
    treatmentAm: 'ልዩ ፀረ-ቫይረስ መድሃኒት የለውም። ቁስልን በፖታሲየም ፐርማንጋኔት ማጽዳት፣ ፀረ-ብግነት መድሃኒት መስጠት፣ ለስላሳ መኖ ማቅረብ፣ ከሌሎች መለየት። ወዲያውኑ ለወረዳ የእንስሳት ጤና ባለሙያ ሪፖርት ያድርጉ።',
    preventionEn: 'Vaccination (trivalent FMD vaccine every 6 months), quarantine new animals for 14 days, restrict animal movement during outbreaks, disinfect footbaths at farm gates.',
    preventionAm: 'በየ6 ወሩ ክትባት (ሶስት ዝርያ የእግርና የአፍ በሽታ ክትባት)፣ አዲስ እንስሳትን 14 ቀን ማግለል፣ በወረርሽኝ ጊዜ የእንስሳት ዝውውርን መቆጣጠር።',
    quarantineRadiusKm: 10,
    seasonalRisk: { KIREMT: 'MODERATE', BELG: 'HIGH', DRY: 'MODERATE' },
  },
  {
    id: 'ANTHRAX',
    nameEn: 'Anthrax (Bacillus anthracis)',
    nameAm: 'አባ ሰንጋ / የአንትራክስ በሽታ',
    nameOm: 'Dhukkuba Abbaa Sangaa',
    animalTypes: ['CATTLE', 'SHEEP', 'GOAT', 'CAMEL', 'EQUINE'],
    category: 'BACTERIAL',
    isZoonotic: true,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'CRITICAL',
    transmissionMode: 'Soil-borne spores, contaminated grazing land, insect bites',
    incubationDays: { min: 1, max: 14 },
    symptomsEn: 'Sudden death (especially cattle), high fever, dark blood from natural orifices (non-clotting), bloating, staggering, convulsions. DO NOT open carcass.',
    symptomsAm: 'ድንገተኛ ሞት (በተለይ ከብት)፣ ከፍተኛ ትኩሳት፣ ከቀዳዳዎች (አፍንጫ፣ ፊንጢጣ) ጥቁር ደም መፍሰስ (የማይረጋ)፣ እብጠት። አስከሬኑን አትክፈቱ!',
    treatmentEn: 'High-dose Penicillin or Oxytetracycline if caught early. Once clinical signs appear, mortality is very high. Carcass must NOT be opened — burn or deep-bury (>2m) with quicklime.',
    treatmentAm: 'ቀደም ብሎ ከተገኘ ከፍተኛ መጠን ፔኒሲሊን ወይም ኦክሲቴትራሳይክሊን። ምልክቶች ከታዩ በኋላ ሞት ያደርሳል። አስከሬኑን አትክፈቱ — ማቃጠል ወይም ጥልቅ ቦታ (ከ2ሜ በላይ) ቆፍሮ ከነጭ ኖራ ጋር መቅበር።',
    preventionEn: 'Annual Sterne spore vaccine, avoid grazing near known burial sites, report sudden deaths immediately, do not consume meat from animals that died suddenly.',
    preventionAm: 'በየዓመቱ የአንትራክስ ክትባት (ስቴርን ስፖር)፣ በሚታወቁ የመቃብር ቦታዎች ዙሪያ አለማሰማራት፣ ድንገተኛ ሞት ወዲያውኑ መዘገብ።',
    quarantineRadiusKm: 15,
    seasonalRisk: { KIREMT: 'HIGH', BELG: 'MODERATE', DRY: 'LOW' },
  },
  {
    id: 'PPR',
    nameEn: 'Peste des Petits Ruminants (PPR / Goat Plague)',
    nameAm: 'ፒፒአር / የፍየልና የበግ ወረርሽኝ',
    nameOm: 'Dhukkuba PPR / Dhibee Re\'ee fi Hoolotaa',
    animalTypes: ['SHEEP', 'GOAT'],
    category: 'VIRAL',
    isZoonotic: false,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'HIGH',
    transmissionMode: 'Direct contact, respiratory droplets, shared feeding/watering',
    incubationDays: { min: 3, max: 10 },
    symptomsEn: 'High fever (40-42°C), mucopurulent nasal and ocular discharge, erosive stomatitis, severe diarrhea (profuse and watery), pneumonia, dehydration. Up to 90% mortality in naive flocks.',
    symptomsAm: 'ከፍተኛ ትኩሳት (40-42°C)፣ ከአፍንጫና ከዓይን ብዛት ያለው መግል ፍሳሽ፣ ከባድ ተቅማጥ (ብዛት ያለው ውሃማ)፣ ሳል/ሳንባ ምች፣ ድርቀት። ክትባት ባላገኙ መንጋዎች 90% ሞት።',
    treatmentEn: 'No antiviral cure. Supportive therapy: rehydration (oral rehydration salts), antibiotics for secondary bacterial infections (Oxytetracycline LA), vitamins.',
    treatmentAm: 'ፀረ-ቫይረስ መድሃኒት የለውም። ድጋፍ ሕክምና: ፈሳሽ ማቅረብ (ORS)፣ ለሁለተኛ ደረጃ ባክቴሪያ ኢንፌክሽን ፀረ-ባክቴሪያ (ኦክሲቴትራሳይክሊን)።',
    preventionEn: 'PPR vaccine (single dose provides lifelong immunity), quarantine infected animals, restrict movement of small ruminants during outbreaks.',
    preventionAm: 'የPPR ክትባት (አንድ ጊዜ ብቻ ዕድሜ ልክ ይከላከላል)፣ የታመሙ እንስሳትን ማግለል፣ በወረርሽኝ ጊዜ ዝውውር መቆጣጠር።',
    quarantineRadiusKm: 5,
    seasonalRisk: { KIREMT: 'MODERATE', BELG: 'HIGH', DRY: 'HIGH' },
  },
  {
    id: 'NCD',
    nameEn: 'Newcastle Disease (NCD)',
    nameAm: 'ፍንጥጥ / የኒውካስል በሽታ',
    nameOm: 'Dhukkuba Fiinxixxii / Newcastle',
    animalTypes: ['POULTRY'],
    category: 'VIRAL',
    isZoonotic: false,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'CRITICAL',
    transmissionMode: 'Aerosol, contaminated feed/water, contact with sick birds or their droppings',
    incubationDays: { min: 2, max: 15 },
    symptomsEn: 'Respiratory distress (gasping, coughing), greenish watery diarrhea, twisted neck (torticollis), paralysis of wings/legs, sudden high mortality (up to 100% in village poultry), drop in egg production.',
    symptomsAm: 'የመተንፈሻ ችግር (ማልሊቃ)፣ አረንጓዴ ውሃማ ተቅማጥ፣ አንገት መጣመም (ቶርቲኮሊስ)፣ የክንፍ/እግር ሽባ፣ ድንገተኛ ከፍተኛ ሞት (እስከ 100%)፣ የእንቁላል ምርት ማሽቆልቆል።',
    treatmentEn: 'No treatment available. Cull affected birds. Improve biosecurity. Thermotolerant I-2 vaccine for village poultry (eye-drop or drinking water).',
    treatmentAm: 'ሕክምና የለውም። የታመሙ ዶሮዎችን ማስወገድ። ባዮሴኪዩሪቲ ማሻሻል። ለገጠር ዶሮዎች I-2 ክትባት (በዓይን ወይም በውሃ)።',
    preventionEn: 'Vaccinate every 3-4 months with HB1 or LaSota strain (spray/drinking water), thermotolerant I-2 for backyard poultry. Quarantine new birds for 2 weeks.',
    preventionAm: 'በየ3-4 ወሩ ክትባት (HB1 ወይም ላሶታ)፣ ለበረንዳ ዶሮ I-2 ክትባት። አዲስ ዶሮዎችን 2 ሳምንት ማግለል።',
    quarantineRadiusKm: 3,
    seasonalRisk: { KIREMT: 'HIGH', BELG: 'MODERATE', DRY: 'MODERATE' },
  },
  {
    id: 'LSD',
    nameEn: 'Lumpy Skin Disease (LSD)',
    nameAm: 'የላም ብጉር በሽታ (LSD)',
    nameOm: 'Dhukkuba Gogaa Tuutuu (LSD)',
    animalTypes: ['CATTLE'],
    category: 'VIRAL',
    isZoonotic: false,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'HIGH',
    transmissionMode: 'Biting insects (mosquitoes, tsetse, stable flies), direct contact',
    incubationDays: { min: 7, max: 28 },
    symptomsEn: 'Fever, firm round skin nodules (2-5 cm diameter) over entire body, enlarged lymph nodes, nasal/ocular discharge, reduced milk yield, emaciation. Hides permanently damaged.',
    symptomsAm: 'ትኩሳት፣ በሰውነት ላይ ክብ ጠንካራ ብጉሮች (2-5 ሴ.ሜ)፣ ሊምፍ ኖዶች ማበጥ፣ ከአፍንጫ/ከዓይን ፍሳሽ፣ የወተት ምርት ቅናሽ፣ ቆዳ ለዘለቄታ ይበላሻል።',
    treatmentEn: 'No antiviral. Supportive care: wound treatment with fly repellent, antibiotics for secondary infections, anti-inflammatory drugs. Isolate infected cattle.',
    treatmentAm: 'ፀረ-ቫይረስ የለም። ቁስል ሕክምና ከዝንብ ማስወገጃ ጋር፣ ለሁለተኛ ደረጃ ኢንፌክሽን ፀረ-ባክቴሪያ፣ ፀረ-ብግነት መድሃኒት። የታመሙ ከብቶችን ማግለል።',
    preventionEn: 'Annual LSD live attenuated vaccine (Neethling strain), insect vector control (insecticide spraying, pour-on), restrict cattle movement during outbreaks.',
    preventionAm: 'በየዓመቱ የLSD ክትባት (ኒትሊንግ ዝርያ)፣ ነፍሳት መቆጣጠሪያ ኬሚካል መርጨት፣ በወረርሽኝ ጊዜ ዝውውር መቆጣጠር።',
    quarantineRadiusKm: 5,
    seasonalRisk: { KIREMT: 'CRITICAL', BELG: 'HIGH', DRY: 'LOW' },
  },
  {
    id: 'BLACKLEG',
    nameEn: 'Blackleg (Clostridial Myositis)',
    nameAm: 'አባ ጎርባ / ብላክ ሌግ',
    nameOm: 'Dhukkuba Abbaa Gorbaa',
    animalTypes: ['CATTLE', 'SHEEP'],
    category: 'BACTERIAL',
    isZoonotic: false,
    isNotifiable: false,
    oieListedDisease: false,
    severity: 'HIGH',
    transmissionMode: 'Soil-borne Clostridium chauvoei spores, wounds, contaminated pasture',
    incubationDays: { min: 1, max: 5 },
    symptomsEn: 'Sudden lameness, swollen and crepitant (crackling) muscles in upper legs/shoulders, high fever, rapid death in young cattle (6 months - 2 years). Affected muscles turn dark/black.',
    symptomsAm: 'ድንገተኛ መላንጠጥ፣ ሰውነትን ከፍ ከፍ ማለት (ጡንቻ ማበጥ)፣ ከፍተኛ ትኩሳት፣ ፈጣን ሞት በወጣት ከብቶች (6 ወር - 2 ዓመት)። የታመመው ጡንቻ ጥቁር ይሆናል።',
    treatmentEn: 'High-dose Penicillin if caught very early. Usually fatal once clinical signs appear. Vaccination is the primary prevention.',
    treatmentAm: 'ቀደም ብሎ ከተገኘ ከፍተኛ ፔኒሲሊን። ምልክት ከታየ በኋላ ሕክምና ብዙም አያዋጣም። ክትባት ዋናው መከላከያ ነው።',
    preventionEn: 'Annual Blackleg vaccine (included in multivalent Clostridial vaccine), vaccinate calves at 3-6 months, avoid grazing in waterlogged or recently flooded pastures.',
    preventionAm: 'በየዓመቱ ብላክሌግ ክትባት (ባለብዙ ዝርያ ክሎስትሪዲያል ክትባት)፣ ጥጃዎችን ከ3-6 ወር ማሰር ክትባት መስጠት።',
    quarantineRadiusKm: 3,
    seasonalRisk: { KIREMT: 'HIGH', BELG: 'MODERATE', DRY: 'LOW' },
  },
  {
    id: 'RVF',
    nameEn: 'Rift Valley Fever (RVF)',
    nameAm: 'ሪፍት ቫሊ ፊቨር',
    nameOm: 'Dhukkuba Rifti Vaalii',
    animalTypes: ['CATTLE', 'SHEEP', 'GOAT', 'CAMEL'],
    category: 'VIRAL',
    isZoonotic: true,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'CRITICAL',
    transmissionMode: 'Mosquito-borne (Aedes, Culex), contact with infected animal blood/tissues',
    incubationDays: { min: 1, max: 6 },
    symptomsEn: 'Abortion storm (almost 100% in pregnant animals), high mortality in neonates/lambs, jaundice, bloody diarrhea, nasal discharge in adults. Zoonotic: causes hemorrhagic fever in humans.',
    symptomsAm: 'ድንገተኛ ማስወረድ (በእርጉዝ እንስሳት 100%)፣ በጨቅላ ግልገሎች ከፍተኛ ሞት፣ ቢጫ ቆዳ/ዓይን (ጃንዲስ)። ለሰውም ይተላለፋል!',
    treatmentEn: 'No treatment. Supportive care only. HIGH ZOONOTIC RISK — wear protective gloves and mask when handling sick animals. Report immediately.',
    treatmentAm: 'ሕክምና የለውም። ድጋፍ ሕክምና ብቻ። ለሰው ከፍተኛ ስጋት — የታመሙ እንስሳትን ሲይዙ ጓንት ያድርጉ። ወዲያውኑ ሪፖርት ያድርጉ!',
    preventionEn: 'RVF vaccine (Smithburn or Clone 13), mosquito control during heavy rains, avoid contact with aborted fetuses, cook meat thoroughly.',
    preventionAm: 'የRVF ክትባት (ስሚዝበርን/ክሎን 13)፣ በከባድ ዝናብ ወቅት ትንኝ መቆጣጠር፣ ከተጣለ ፅንስ ጋር ያለመንካት።',
    quarantineRadiusKm: 20,
    seasonalRisk: { KIREMT: 'CRITICAL', BELG: 'HIGH', DRY: 'LOW' },
  },
  {
    id: 'BOVINE_TB',
    nameEn: 'Bovine Tuberculosis (bTB)',
    nameAm: 'የከብት ቲቢ / ሳንባ ነቀርሳ',
    nameOm: 'Dhukkuba Somba Loowanii (TB)',
    animalTypes: ['CATTLE'],
    category: 'BACTERIAL',
    isZoonotic: true,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'HIGH',
    transmissionMode: 'Aerosol, contaminated milk (unpasteurized), close confinement',
    incubationDays: { min: 30, max: 365 },
    symptomsEn: 'Chronic progressive wasting, persistent cough, enlarged lymph nodes (especially retropharyngeal and mediastinal), reduced milk yield, intermittent fever.',
    symptomsAm: 'ቀስ በቀስ ማጨስ/ማቃጠል፣ ተደጋጋሚ ሳል፣ ሊምፍ ኖዶች ማበጥ፣ የወተት ምርት ማሽቆልቆል፣ ዝቅተኛ ትኩሳት። ለሰው ይተላለፋል (ባልበሰለ ወተት)!',
    treatmentEn: 'No practical treatment in livestock. Test-and-slaughter policy in affected herds. Pasteurize all milk before consumption. Zoonotic risk through raw milk.',
    treatmentAm: 'በእንስሳት ላይ ተግባራዊ ሕክምና የለም። ምርመራና ማረድ ፖሊሲ። ወተትን ሳይፈላ/ሳይስክ አለመጠጣት። ባልበሰለ ወተት ለሰው ይተላለፋል!',
    preventionEn: 'BCG vaccination (limited efficacy), tuberculin skin testing, pasteurize milk, improve ventilation in zero-grazing units, test-and-slaughter program.',
    preventionAm: 'BCG ክትባት (ውስን ውጤታማነት)፣ ቱበርኩሊን ቆዳ ምርመራ፣ ወተት ማፍላት/ማስክ፣ ዜሮ ግራዚንግ ክፍሎች አየር ማስተንፈስ ማሻሻል።',
    quarantineRadiusKm: 5,
    seasonalRisk: { KIREMT: 'MODERATE', BELG: 'MODERATE', DRY: 'MODERATE' },
  },
  {
    id: 'AVIAN_INFLUENZA',
    nameEn: 'Avian Influenza (Bird Flu)',
    nameAm: 'የወፍ ጉንፋን / ኤቪያን ኢንፍሉዌንዛ',
    nameOm: 'Dhukkuba Qufaa Simbirroo',
    animalTypes: ['POULTRY'],
    category: 'VIRAL',
    isZoonotic: true,
    isNotifiable: true,
    oieListedDisease: true,
    severity: 'CRITICAL',
    transmissionMode: 'Direct contact with infected birds, contaminated surfaces, wild bird migration',
    incubationDays: { min: 1, max: 7 },
    symptomsEn: 'Sudden high mortality (up to 100%), swollen head and comb (cyanotic/dark), respiratory distress, watery diarrhea, drop in egg production, hemorrhages on shanks.',
    symptomsAm: 'ድንገተኛ ከፍተኛ ሞት (100%)፣ ጭንቅላትና ኮምብ ማበጥ (ሰማያዊ/ጥቁር)፣ የመተንፈሻ ችግር፣ ውሃማ ተቅማጥ፣ እንቁላል ማሽቆልቆል።',
    treatmentEn: 'No treatment. Stamping out (complete depopulation) of affected flocks. Strict biosecurity. HIGHLY ZOONOTIC — avoid direct contact. Report immediately.',
    treatmentAm: 'ሕክምና የለም። የታመሙ መንጋዎችን ሙሉ በሙሉ ማስወገድ። ጥብቅ ባዮሴኪዩሪቲ። ለሰው ከፍተኛ ስጋት — ከታመሙ ዶሮዎች አለመንካት!',
    preventionEn: 'Strict biosecurity (no wild bird contact), avoid live bird markets mixing, surveillance of migratory bird routes, report any unusual poultry deaths.',
    preventionAm: 'ጥብቅ ባዮሴኪዩሪቲ (ከዱር ወፎች ጋር ያለመነካካት)፣ ያልተለመደ የዶሮ ሞት ወዲያውኑ ማሳወቅ።',
    quarantineRadiusKm: 10,
    seasonalRisk: { KIREMT: 'MODERATE', BELG: 'LOW', DRY: 'HIGH' },
  },
  {
    id: 'TRYPANOSOMIASIS',
    nameEn: 'Trypanosomiasis (Nagana / Tsetse-borne)',
    nameAm: 'ጋንዲ / ትሪፓኖሶሚያሲስ',
    nameOm: 'Dhukkuba Gaandii / Tiripaanosoomiyaasis',
    animalTypes: ['CATTLE', 'EQUINE', 'CAMEL'],
    category: 'PARASITIC',
    isZoonotic: false,
    isNotifiable: false,
    oieListedDisease: true,
    severity: 'HIGH',
    transmissionMode: 'Tsetse fly (Glossina) bite, mechanical transmission by biting flies',
    incubationDays: { min: 7, max: 21 },
    symptomsEn: 'Intermittent fever, progressive anemia (pale mucous membranes), weight loss, rough coat, lacrimation, edema (especially submandibular — "bottle jaw"), weakness, death if untreated.',
    symptomsAm: 'ተደጋጋሚ ትኩሳት፣ ቀስ በቀስ ደም ማነስ (ነጭ ምስጢራዊ ሽፋን)፣ ክብደት ማጣት፣ ያልተሰካ ፀጉር፣ ድክመት። ካልታከመ ሞት ያስከትላል።',
    treatmentEn: 'Diminazene aceturate (Berenil) 3.5 mg/kg IM or Isometamidium chloride (Samorin) 0.5-1.0 mg/kg IM. May need repeated treatment.',
    treatmentAm: 'ዲሚናዚን (ቤሬኒል) 3.5 ሚ.ግ/ኪ.ግ IM ወይም ኢሶሜታሚዲየም (ሳሞሪን) 0.5-1.0 ሚ.ግ/ኪ.ግ IM።',
    preventionEn: 'Tsetse fly traps (blue-black targets with insecticide), pour-on insecticides, Sterile Insect Technique (SIT), use trypanotolerant breeds (Sheko cattle).',
    preventionAm: 'ጤጤ ዝንብ ወጥመድ፣ ፀረ-ነፍሳት ኬሚካል (pour-on)፣ ጤጤ ዝንብ የሚቋቋሙ ዝርያዎችን ማሳደግ (ሸኮ ከብት)።',
    quarantineRadiusKm: 0,
    seasonalRisk: { KIREMT: 'CRITICAL', BELG: 'HIGH', DRY: 'MODERATE' },
  },
];

// Ethiopian livestock breed reference
const ETHIOPIAN_LIVESTOCK_BREEDS = {
  CATTLE: [
    { breed: 'Boran', origin: 'Borana Zone, Oromia', type: 'Zebu', primaryUse: 'Beef, Milk, Draft', heatTolerant: true },
    { breed: 'Horro', origin: 'Horro Guduru Wollega, Oromia', type: 'Zebu', primaryUse: 'Milk, Draft', heatTolerant: false },
    { breed: 'Sheko', origin: 'Bench Sheko, SNNPR', type: 'Taurine (Trypanotolerant)', primaryUse: 'Milk, Beef', heatTolerant: true },
    { breed: 'Arsi', origin: 'Arsi Zone, Oromia', type: 'Zebu', primaryUse: 'Draft, Milk', heatTolerant: false },
    { breed: 'Fogera', origin: 'South Gondar, Amhara', type: 'Zebu', primaryUse: 'Milk, Draft', heatTolerant: false },
    { breed: 'Begait/Barka', origin: 'Tigray (lowland)', type: 'Sanga', primaryUse: 'Milk, Beef', heatTolerant: true },
  ],
  SHEEP: [
    { breed: 'Menz', origin: 'North Shewa, Amhara', type: 'Fat-tailed', primaryUse: 'Wool, Meat', coldTolerant: true },
    { breed: 'Horro', origin: 'Wollega, Oromia', type: 'Fat-tailed', primaryUse: 'Meat', coldTolerant: false },
    { breed: 'Blackhead Somali (BHS)', origin: 'Somali Region', type: 'Fat-rumped', primaryUse: 'Meat, Milk', heatTolerant: true },
    { breed: 'Washera', origin: 'West Gojjam, Amhara', type: 'Fat-tailed', primaryUse: 'Meat', coldTolerant: true },
    { breed: 'Afar', origin: 'Afar Region', type: 'Thin-tailed', primaryUse: 'Meat, Milk', heatTolerant: true },
  ],
  GOAT: [
    { breed: 'Arsi-Bale', origin: 'Arsi/Bale, Oromia', type: 'Highland', primaryUse: 'Milk, Meat' },
    { breed: 'Somali/Ogaden', origin: 'Somali Region', type: 'Long-eared', primaryUse: 'Milk, Meat', heatTolerant: true },
    { breed: 'Afar', origin: 'Afar Region', type: 'Lowland', primaryUse: 'Milk, Meat', heatTolerant: true },
    { breed: 'Woyto-Guji', origin: 'South Omo/Guji', type: 'Highland', primaryUse: 'Meat' },
    { breed: 'Central Highland', origin: 'Central Highlands', type: 'Highland', primaryUse: 'Meat, Skin' },
  ],
  CAMEL: [
    { breed: 'Afar Dromedary', origin: 'Afar Region', type: 'Dromedary', primaryUse: 'Milk, Transport', heatTolerant: true },
    { breed: 'Issa/Somali Dromedary', origin: 'Somali Region', type: 'Dromedary', primaryUse: 'Milk, Meat, Transport', heatTolerant: true },
  ],
  POULTRY: [
    { breed: 'Horro', origin: 'Western Oromia', type: 'Indigenous', primaryUse: 'Eggs, Meat' },
    { breed: 'Fayoumi', origin: 'Imported (Egypt)', type: 'Exotic', primaryUse: 'Eggs' },
    { breed: 'Koekoek', origin: 'Imported (South Africa)', type: 'Dual-purpose', primaryUse: 'Eggs, Meat' },
    { breed: 'Tilili', origin: 'Northwestern Highlands', type: 'Indigenous', primaryUse: 'Eggs, Meat' },
  ],
  EQUINE: [
    { breed: 'Oromo Horse', origin: 'Oromia', type: 'Light Horse', primaryUse: 'Transport, Draft' },
    { breed: 'Ethiopian Donkey', origin: 'Nationwide', type: 'Donkey', primaryUse: 'Pack Transport' },
    { breed: 'Wollo Mule', origin: 'Amhara Highlands', type: 'Mule', primaryUse: 'Pack Transport (Highland)' },
  ],
};

function getDiseaseById(id) {
  return LIVESTOCK_DISEASES.find((d) => d.id === id) || null;
}

function getDiseasesByAnimalType(animalType) {
  return LIVESTOCK_DISEASES.filter((d) => d.animalTypes.includes(animalType.toUpperCase()));
}

function getZoonoticDiseases() {
  return LIVESTOCK_DISEASES.filter((d) => d.isZoonotic);
}

function getNotifiableDiseases() {
  return LIVESTOCK_DISEASES.filter((d) => d.isNotifiable);
}

function getSeasonalHighRiskDiseases(season = 'KIREMT') {
  return LIVESTOCK_DISEASES.filter((d) => {
    const risk = d.seasonalRisk[season];
    return risk === 'CRITICAL' || risk === 'HIGH';
  });
}

module.exports = {
  LIVESTOCK_DISEASES,
  ETHIOPIAN_LIVESTOCK_BREEDS,
  getDiseaseById,
  getDiseasesByAnimalType,
  getZoonoticDiseases,
  getNotifiableDiseases,
  getSeasonalHighRiskDiseases,
};
